# Generated by Django 5.1.6 on 2026-07-01 08:29

import apps.invitations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('program', 'Programme'), ('group', 'Groupe')], default='program', max_length=10, verbose_name='type')),
                ('group_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='groupe (id)')),
                ('target_type', models.CharField(choices=[('member', 'Membre existant'), ('contact', 'Contact externe')], default='member', max_length=10, verbose_name='type de cible')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='contact externe')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('expired', 'Expirée')], default='pending', max_length=10, verbose_name='statut')),
                ('expires_at', models.DateTimeField(default=apps.invitations.models.default_expires_at, verbose_name='expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('from_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
