# Generated by Django 5.1.6 on 2026-07-01 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('kind', models.CharField(choices=[('personal', 'Personnel'), ('coach_shared', 'Coaché partagé')], default='personal', max_length=20, verbose_name='type')),
                ('objective', models.CharField(blank=True, max_length=100, verbose_name='objectif')),
                ('level', models.CharField(blank=True, max_length=30, verbose_name='niveau')),
                ('duration_days', models.PositiveSmallIntegerField(default=30, verbose_name='durée (jours)')),
                ('is_shared', models.BooleanField(default=False, verbose_name='partagé')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('generated_by', models.CharField(choices=[('ai', 'IA'), ('coach', 'Coach')], default='coach', max_length=10, verbose_name='généré par')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='gyms.gym')),
                ('member', models.ForeignKey(blank=True, help_text='null = template partagé non assigné.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
                ('owner_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coached_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'programme',
                'verbose_name_plural': 'programmes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='1=lundi … 7=dimanche', null=True, verbose_name='jour de la semaine')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.program')),
            ],
            options={
                'verbose_name': 'jour de programme',
                'verbose_name_plural': 'jours de programme',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='séries')),
                ('reps', models.PositiveSmallIntegerField(default=10, verbose_name='répétitions')),
                ('charge', models.CharField(blank=True, max_length=50, verbose_name='charge')),
                ('rest_s', models.PositiveSmallIntegerField(default=90, verbose_name='repos (s)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='catalog.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.programday')),
            ],
            options={
                'verbose_name': "prescription d'exercice",
                'verbose_name_plural': "prescriptions d'exercices",
                'ordering': ['program_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('dropped', 'Abandonnée')], default='active', max_length=10, verbose_name='statut')),
                ('sessions_done', models.PositiveSmallIntegerField(default=0, verbose_name='séances faites')),
                ('sessions_target', models.PositiveSmallIntegerField(default=0, verbose_name='séances prévues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_enrollments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program')),
            ],
            options={
                'verbose_name': 'adhésion',
                'verbose_name_plural': 'adhésions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'program', 'start_date'), name='unique_enrollment_member_program_start')],
            },
        ),
    ]
