# Generated by Django 5.1.6 on 2026-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('muscle', models.CharField(blank=True, max_length=80, verbose_name='muscle')),
                ('default_sets', models.PositiveSmallIntegerField(default=3, verbose_name='séries par défaut')),
                ('default_reps', models.PositiveSmallIntegerField(default=10, verbose_name='répétitions par défaut')),
                ('default_rest_s', models.PositiveSmallIntegerField(default=90, verbose_name='repos par défaut (s)')),
                ('charge_hint', models.CharField(blank=True, max_length=50, verbose_name='indication de charge')),
                ('video_url', models.URLField(blank=True, verbose_name='vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='vignette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exercice',
                'verbose_name_plural': 'exercices',
                'ordering': ['name'],
            },
        ),
    ]
