# Generated by Django 5.1.6 on 2026-06-30 16:09

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='téléphone')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='nom complet')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('coach', 'Coach'), ('manager', 'Gérant'), ('admin', 'Admin')], default='member', max_length=10, verbose_name='rôle')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='équipe')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(blank=True, max_length=50, verbose_name='objectif')),
                ('level', models.CharField(blank=True, max_length=30, verbose_name='niveau')),
                ('weekly_freq', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='fréquence hebdo')),
                ('theme_mode', models.CharField(choices=[('dark', 'Dark'), ('rose', 'Rose')], default='dark', max_length=10, verbose_name='thème')),
                ('accent_color', models.CharField(default='#5fe3f0', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit être un code hexadécimal valide (ex. #5fe3f0).', regex='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name="couleur d'accent")),
                ('voice_cues', models.BooleanField(default=True, verbose_name='indications vocales')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='taille (cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
    ]
